language: node_js
node_js:
- '8'
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: L8uhLZikY0GNp3TC80f66ZktwPSDUcgGIWfNXBmrOOeCU3rAkSUEgYASAFiJlOkiv70ZlEjjb5sQ6AoItpKeAmnt0mpYDvN+Ln4QpXCqNf37hQv81V1XLtHIR1icYDJ6H2JaqHxw3t05TJ9r3z5owtog0bbqZGuoXTHOsUswUUAk1TNttyEwk8Ztq3dEmeAUzg1Qbh1YzZ63Om9WAoE/TQ2Uh7Dx6I3QPgndAL0r1S2eDgoBMtbc4qOMS3PqN+G4W3EgbBrIK3JN22rNpDViqDmQKOoP7u5PBtbH3FEEkpTtTeYeB05y9jaktbZd5/MnnTtc2XI9FCURHWPUU+IJTGN/V7UXNt9uSUgox5L+OVUGALhil5zj+JeFl9Svgzhgu6N350qOmorADGNL7fDcqRNYBwyl+VMGBF5WmcqfkfpRAGr3C/W1G4Ls3GQwIh8eAgS9vLklcrubwmOkUUwX2dtwRRNBmb3NW6GIPGdsKWncjQT5k/stMeXac0VtKffCCLWZt9Tt2PVj3c8rD59G5Qe+8x0VluD8OCdQuNJJ7Nd6zX0+QtFe39fCMwxa6vbgMnI5fbN+rmNeZ8WM+JVMrIWQ0W/iAkjrHvtGaMg2M8PxSGqK/njNtWvh/wy/JwjPWNHS969GcND4C+SEFuzh/nO0Izrzq6IAgrxo5X81ALU=
  app: desolate-bastion-38007
  on:
    repo: synedra/test_deploy
